language: node_js

node_js: "12"

services:
  - docker

before_install:
# Install AZ CLI
- AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo apt-get install apt-transport-https
- sudo apt-get update && sudo apt-get install azure-cli

install:
- export DOCKER_FULL_IMAGE_NAME=$ACR_NAME.azurecr.io/$DOCKER_IMAGE_NAME:$TRAVIS_COMMIT
- docker build -t $DOCKER_FULL_IMAGE_NAME .

deploy:
  provider: script
  on:
    branch: master
  script: bash scripts/docker_push
